name: Build gear loader

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BINARYEN_VERSION: version_111

jobs:
  build-gear-loader:
    runs-on: [kuberunner]
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - name: "ACTIONS: Checkout"
        run: |
          echo "$GITHUB_REF"

  update-gear-loader:
    runs-on: ubuntu-latest
    needs: build-gear-loader
    steps:
      - name: "ACTIONS: Checkout"
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gear-loader

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible/
          playbook: gear-loader-update.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.GEAR_LOADER_NODE}}
